name: CI
on:
  pull_request:
    branches:
      - production
      - development
      - master
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout do repositorio
         uses: actions/checkout@v1
       - name: Setup Node
         uses: actions/setup-node@v1
         with:
           node-version: "18.x" 
       - name: Install dependencies
         run: npm i
       - name: Check lint
         run: npm lint:test
       - name: Check types
         run: npm run typecheck
      #  - name: Running tests
      #    run: npm run test:coverage:silent